### ISSUE TITLE
test/package.json is a required file for all projects using lambda-cfn

### ISSUE THREAD

**Issue by oliikit** [mapbox/lambda-cfn#52]
I'm getting the following error when I run tests using a project with lambda-cfn as a devdependency:

```console
module.js:327
    throw err;
    ^

Error: Cannot find module '/../test/package.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/../node_modules/lambda-cfn/lib/lambda-cfn.js:47:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Going through the stack trace, this is caused by the following code in `lambda-cfn.js` at line 45:
```js
var pkgs;
if (process.env.NODE_ENV == 'test') {
    pkgs = require(path.join(root,'test/package.json'));
} else {
    pkgs = require(path.join(root,'package.json'));
}
```

It seems this code is needed for lambda-cfn tests to run. But because of this, it requires `test/package.json` to exist to all projects using this package - which shouldn't be the case.

**Comment by zmully** [comment]
N/A with lamdba-cfn v2.0.0+
